- uses: browser-actions/setup-chrome@v1
  with:
    # The Google Chrome/Chromium version to install and use.
    chrome-version: "latest"
    # Install dependent packages for Google Chrome/Chromium (
    # Linux only).
    install-dependencies: "false"
    # Install the compatible version of ChromeDriver with the
    # installed Google Chrome/Chromium.
    install-chromedriver: "false"
    # Do not use sudo to install Google Chrome/Chromium (Linux
    # only).
    no-sudo: "false
